# run: conda env create -f conda_env.yml
name: viewer
dependencies:
  - numpy
  - pandas
  - scipy
  - ipython
  - pip
  - pip:
    - h5py
    - PyQt6
    - pyqtgraph
    - opencv-python
    - ffmpy
    - tifffile